from . import test_saas_client
from . import test_config
from . import test_acl_coverage
from . import test_i18n_file
from . import test_map_widget_options
from . import test_map_widget_registration
from . import test_guard_contract
from . import test_res_config_settings
from . import test_plan_features
from . import test_presenly_endpoints
from . import test_monitoring
from . import test_monitoring_fields
from . import test_submissions
from . import test_approval
from . import test_retention
from . import test_timesheets
