{
    'name': 'KSG Operational Management',
    'version': '19.0.1.0.0',
    'category': 'Operations',
    'summary': 'Manajemen Operasional: SDM, Perlengkapan, Pengadaan Dana, Presensi, BAST, & Laporan Pekerjaan',
    'author': 'Dewa Bagus Martsetyo - PT Multi Clean Global',
    'depends': ['base', 'mail', 'ksg_sales'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_sequence_payment_data.xml',
        'data/ir_cron_data.xml',
        'views/reject_wizard_views.xml',
        'views/manpower_request_views.xml',
        'views/supply_request_views.xml',
        'views/operational_payment_views.xml',
        'views/operational_assignment_views.xml',
        'views/attendance_views.xml',
        'views/bast_views.xml',
        'views/work_report_views.xml',
        'views/work_report_templates.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}