services:
  web:
    image: odoo:19.0

    ports:
      - "8099:8069"

    command: >
      bash -c "
      odoo
      -d db_sifnext
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      -u sifnext_operational,sif_rka,sifnext_ppl,presenly,presenly_payroll
      --stop-after-init
      &&
      exec odoo
      -d db_sifnext
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --proxy-mode
      "

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons

    env_file:
      - .env

    networks:
      - dokploy-network

    restart: unless-stopped

volumes:
  odoo-web-data:

networks:
  dokploy-network:
    external: true
